In [1]:
%pip install pandas numpy

Requirement already satisfied: pandas in c:\users\dikshant\appdata\local\programs\python\python311\lib\site-packages (3.0.5)
Requirement already satisfied: numpy in c:\users\dikshant\appdata\local\programs\python\python311\lib\site-packages (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\dikshant\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\dikshant\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\dikshant\appdata\local\programs\python\python311\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip available: 22.3 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv( r"C:\Users\dikshant\OneDrive\Desktop\jupyter notebook\Banking_Data_Analytics_2000_Rows.csv")

In [3]:
df

,Customer_ID,Customer_Name,Age,Gender,City,State,Occupation,Account_Type,Annual_Income,Account_Balance,Credit_Score,Transactions_Per_Month,Loan_Type,Loan_Amount,Interest_Rate,Payment_Channel,Tenure_Years,Customer_Satisfaction,Churn
0,100001,Vivaan,55,Male,Kolkata,West Bengal,Retired,Savings,16300.0,582230.23,784.0,24,NaN,0.0,0.00,Debit Card,5,4.1,No
1,100002,Nikhil,41,Female,Bengaluru,Karnataka,Salaried,Savings,42700.0,24690.72,736.0,20,NaN,0.0,0.00,Branch,20,4.0,No
2,100003,Sneha,36,Male,Gurugram,Haryana,Salaried,Current,62200.0,29627.96,730.0,15,NaN,0.0,0.00,Debit Card,1,3.7,No
3,100004,Ananya,37,Male,Jaipur,Rajasthan,Business,Salary,73700.0,50463.73,637.0,8,Home,548700.0,10.97,Credit Card,9,2.8,No
4,100005,Sneha,43,Female,Hyderabad,Telangana,Professional,Savings,39500.0,239069.97,635.0,21,Home,775800.0,15.75,ATM,15,3.7,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,101996,Pooja,42,Male,Kolkata,West Bengal,Self-Employed,Savings,71200.0,78820.05,753.0,18,NaN,0.0,0.00,Debit Card,20,2.9,Yes
1996,101997,Ananya,49,Male,Hyderabad,Telangana,Professional,Savings,53000.0,474056.04,722.0,13,NaN,0.0,0.00,Net Banking,12,4.0,No
1997,101998,Vivaan,31,Female,Kolkata,West Bengal,Self-Employed,Current,34100.0,17366.53,815.0,16,NaN,0.0,0.00,Debit Card,4,3.5,No
1998,101999,Karan,31,Male,Pune,Maharashtra,Student,Current,48700.0,45439.75,643.0,19,NaN,0.0,0.00,ATM,10,3.5,No
1999,102000,Aditya,49,Female,Ahmedabad,Gujarat,Business,Savings,19400.0,77235.80,NaN,20,Business,215800.0,13.26,Debit Card,30,3.7,No

In [4]:
# 🏦 Banking Dataset — 20 Questions

# Q1. Dataset Overview
# Find the number of rows, number of columns, column names, data types, missing values, and unique values.

# Q2. Age Analysis
# Find the mean, median, minimum, maximum, and standard deviation of customer age.

# Q3. Income Analysis
# Find the mean, median, minimum, maximum, standard deviation, and 25th/50th/75th percentiles of Annual_Income.

# Q4. Account Balance Analysis
# Find the mean, median, minimum, maximum, and standard deviation of Account_Balance. Also find how many customers have a balance greater than ₹10,00,000.

# Q5. Gender Analysis
# For each gender, find the number of customers and average Annual_Income, Account_Balance, Credit_Score, and Customer_Satisfaction.

# Q6. Occupation Analysis
# Find the number of customers in each occupation and calculate the average income and account balance for each occupation.

# Q7. City Analysis
# Find the top 10 cities having the highest number of customers.

# Q8. Account Type Analysis
# For each Account_Type, find the number of customers, average account balance, average income, and average monthly transactions.

# Q9. Credit Score Classification
# Create these categories based on Credit_Score:

# Excellent → 750+
# Good → 700–749
# Average → 650–699
# Poor → Below 650

# Then find the number of customers in each category.

# Q10. Loan Analysis
# Find:

# Total number of customers having a loan
# Total loan amount
# Average loan amount
# Median loan amount
# Average interest rate
# Most common loan type

# Q11. High-Risk Customers
# Find customers who satisfy at least two of these conditions:

# Credit score < 650
# Loan amount > ₹10,00,000
# Interest rate > 15%
# Account balance < ₹20,000

# Display their Customer_ID, Customer_Name, Credit_Score, Loan_Amount, Interest_Rate, and Account_Balance.

# Q12. Correlation Analysis
# Find the correlation between:

# Annual_Income and Loan_Amount
# Credit_Score and Loan_Amount
# Annual_Income and Account_Balance
# Transactions_Per_Month and Account_Balance

# Q13. Outlier Detection — IQR
# Using the IQR method, detect outliers in:

# Annual_Income
# Account_Balance
# Loan_Amount

# Find Q1, Q3, IQR, lower limit, upper limit, and number of outliers.

# Q14. Z-Score Analysis
# Calculate the Z-score for:

# Annual_Income
# Account_Balance
# Credit_Score
# Loan_Amount

# Find customers whose absolute Z-score is greater than 3.

# Q15. Log-Normal Distribution Analysis
# Check whether Annual_Income, Account_Balance, and Loan_Amount are right-skewed.

# Calculate their skewness before and after applying log1p() and compare the results.



# Q16. Customer Segmentation
# Divide customers into four groups based on income and account balance:

# High Income + High Balance
# High Income + Low Balance
# Low Income + High Balance
# Low Income + Low Balance

# Compare the number of customers, average credit score, average transactions, and churn rate for each segment.

In [5]:
# Q1. Dataset Overview
# Find the number of rows, number of columns, column names, data types, missing values, and unique values.
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 19 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer_ID             2000 non-null   int64
 1   Customer_Name           2000 non-null   str
 2   Age                     2000 non-null   int64
 3   Gender                  2000 non-null   str
 4   City                    2000 non-null   str
 5   State                   2000 non-null   str
 6   Occupation              1970 non-null   str
 7   Account_Type            2000 non-null   str
 8   Annual_Income           2000 non-null   float64
 9   Account_Balance         1975 non-null   float64
 10  Credit_Score            1965 non-null   float64
 11  Transactions_Per_Month  2000 non-null   int64
 12  Loan_Type               981 non-null    str
 13  Loan_Amount             2000 non-null   float64
 14  Interest_Rate           2000 non-null   float64
 15  Payment_Channel         2000 non-null   str
 16  Tenure_Years            2000 non-null   int64
 17  Customer_Satisfaction   1970 non-null   float64
 18  Churn                   2000 non-null   str
dtypes: float64(6), int64(4), str(9)
memory usage: 297.0 KB

In [6]:
df.isnull().sum()

Customer_ID                  0
Customer_Name                0
Age                          0
Gender                       0
City                         0
State                        0
Occupation                  30
Account_Type                 0
Annual_Income                0
Account_Balance             25
Credit_Score                35
Transactions_Per_Month       0
Loan_Type                 1019
Loan_Amount                  0
Interest_Rate                0
Payment_Channel              0
Tenure_Years                 0
Customer_Satisfaction       30
Churn                        0
dtype: int64

In [7]:
df.nunique()

Customer_ID               2000
Customer_Name               20
Age                         54
Gender                       2
City                        12
State                       10
Occupation                   6
Account_Type                 3
Annual_Income             1016
Account_Balance           1975
Credit_Score               300
Transactions_Per_Month      30
Loan_Type                    5
Loan_Amount                938
Interest_Rate              675
Payment_Channel              6
Tenure_Years                30
Customer_Satisfaction       39
Churn                        2
dtype: int64

In [8]:
 # Q2. Age Analysis
# Find the mean, median, minimum, maximum, and standard deviation of customer age.
df["Age"].mean()
# df["Age"].median()
# df["Age"].mode()
# df["Age"].std()

np.float64(36.5475)

In [9]:
df["Age"].median()

np.float64(36.0)

In [10]:
 df["Age"].mode()

0    18
Name: Age, dtype: int64

In [11]:
 df["Age"].std()

np.float64(10.465300043596516)

In [12]:
max = df["Age"].max()
print(max)

75

In [13]:
min = df["Age"].min()
print(min)

18

In [14]:
# Q3. Income Analysis
# Find the mean, median, minimum, maximum, standard deviation, and 25th/50th/75th percentiles of Annual_Income.
df["Annual_Income"].mean()
# df["Annual_Income"].median()
# df["Annual_Income"].mode()
# df["Annual_Income"].std()

np.float64(70074.922)

In [15]:
df["Annual_Income"].median()
# df["Annual_Income"].mode()
# df["Annual_Income"].std()

np.float64(54850.0)

In [16]:
df["Annual_Income"].mode()
# df["Annual_Income"].std()

0    10000.0
Name: Annual_Income, dtype: float64

In [17]:
df["Annual_Income"].std()

np.float64(74630.86071667385)

In [18]:
df["Annual_Income"].min()

np.float64(10000.0)

In [19]:
df["Annual_Income"].max()

np.float64(1199563.0)

In [20]:
df["Annual_Income"].quantile(.25)

np.float64(34575.0)

In [21]:
df["Annual_Income"].quantile(.50)

np.float64(54850.0)

In [22]:
df["Annual_Income"].quantile(.75)

np.float64(84450.0)

In [23]:
# Q4. Account Balance Analysis
# Find the mean, median, minimum, maximum, and standard deviation of Account_Balance. 
# Also find how many customers have a balance greater than ₹10,00,000.
df["Account_Balance"].info()

<class 'pandas.Series'>
RangeIndex: 2000 entries, 0 to 1999
Series name: Account_Balance
Non-Null Count  Dtype
--------------  -----
1975 non-null   float64
dtypes: float64(1)
memory usage: 15.8 KB

In [24]:
df["Annual_Income"].describe()

count    2.000000e+03
mean     7.007492e+04
std      7.463086e+04
min      1.000000e+04
25%      3.457500e+04
50%      5.485000e+04
75%      8.445000e+04
max      1.199563e+06
Name: Annual_Income, dtype: float64

In [25]:
df["Account_Balance"].describe()

count    1.975000e+03
mean     1.281253e+05
std      3.102548e+05
min      5.517500e+03
25%      3.926620e+04
50%      7.226390e+04
75%      1.388458e+05
max      5.969984e+06
Name: Account_Balance, dtype: float64

In [26]:
# Also find how many customers have a balance greater than ₹10,00,000.
res = (df["Account_Balance"] > 1000000).sum()
print(res)

13

In [27]:
 # Q5. Gender Analysis
# For each gender, find the number of customers and average Annual_Income, Account_Balance, Credit_Score, and Customer_Satisfaction.

# Q6. Occupation Analysis
# Find the number of customers in each occupation and calculate the average income and account balance for each occupation.

# Q7. City Analysis
# Find the top 10 cities having the highest number of customers.

# Q8. Account Type Analysis
# For each Account_Type, find the number of customers, average account balance, average income, and average monthly transactions.

# Q9. Credit Score Classification
# Create these categories based on Credit_Score:

# Excellent → 750+
# Good → 700–749
# Average → 650–699
# Poor → Below 650

# Then find the number of customers in each category.

# Q10. Loan Analysis
# Find:

# Total number of customers having a loan
# Total loan amount
# Average loan amount
# Median loan amount
# Average interest rate
# Most common loan type

# Q11. High-Risk Customers
# Find customers who satisfy at least two of these conditions:

# Credit score < 650
# Loan amount > ₹10,00,000
# Interest rate > 15%
# Account balance < ₹20,000

# Display their Customer_ID, Customer_Name, Credit_Score, Loan_Amount, Interest_Rate, and Account_Balance.

# Q12. Correlation Analysis
# Find the correlation between:

# Annual_Income and Loan_Amount
# Credit_Score and Loan_Amount
# Annual_Income and Account_Balance
# Transactions_Per_Month and Account_Balance

# Q13. Outlier Detection — IQR
# Using the IQR method, detect outliers in:

# Annual_Income
# Account_Balance
# Loan_Amount

# Find Q1, Q3, IQR, lower limit, upper limit, and number of outliers.

# Q14. Z-Score Analysis
# Calculate the Z-score for:

# Annual_Income
# Account_Balance
# Credit_Score
# Loan_Amount

# Find customers whose absolute Z-score is greater than 3.

# Q15. Log-Normal Distribution Analysis
# Check whether Annual_Income, Account_Balance, and Loan_Amount are right-skewed.

# Calculate their skewness before and after applying log1p() and compare the results.

.

# Q16. Customer Segmentation
# Divide customers into four groups based on income and account balance:

# High Income + High Balance
# High Income + Low Balance
# Low Income + High Balance
# Low Income + Low Balance

# Compare the number of customers, average credit score, average transactions, and churn rate for each segment.

In [28]:
 # Q5. Gender Analysis
# For each gender, find the number of customers and average Annual_Income, Account_Balance, Credit_Score, and Customer_Satisfaction.
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 19 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer_ID             2000 non-null   int64
 1   Customer_Name           2000 non-null   str
 2   Age                     2000 non-null   int64
 3   Gender                  2000 non-null   str
 4   City                    2000 non-null   str
 5   State                   2000 non-null   str
 6   Occupation              1970 non-null   str
 7   Account_Type            2000 non-null   str
 8   Annual_Income           2000 non-null   float64
 9   Account_Balance         1975 non-null   float64
 10  Credit_Score            1965 non-null   float64
 11  Transactions_Per_Month  2000 non-null   int64
 12  Loan_Type               981 non-null    str
 13  Loan_Amount             2000 non-null   float64
 14  Interest_Rate           2000 non-null   float64
 15  Payment_Channel         2000 non-null   str
 16  Tenure_Years            2000 non-null   int64
 17  Customer_Satisfaction   1970 non-null   float64
 18  Churn                   2000 non-null   str
dtypes: float64(6), int64(4), str(9)
memory usage: 297.0 KB

In [29]:
result = df["Gender"].info()

<class 'pandas.Series'>
RangeIndex: 2000 entries, 0 to 1999
Series name: Gender
Non-Null Count  Dtype
--------------  -----
2000 non-null   str
dtypes: str(1)
memory usage: 15.8 KB

In [30]:
# So for this particular question, I recommend the first .groupby().agg() solution.
Gender_analyse = df.groupby("Gender").agg(
    average_Annual_Income=("Annual_Income","mean"),
    average_Account_Balance = ("Account_Balance","mean"),
     average_Credit_Score=("Credit_Score","mean"),
    average_Customer_Satisfaction=("Customer_Satisfaction","mean")
)
print(Gender_analyse)

        average_Annual_Income  average_Account_Balance  average_Credit_Score  \
Gender
Female           69770.340355            124524.462918            712.697175
Male             70325.133880            131085.055129            708.844444

        average_Customer_Satisfaction
Gender
Female                       3.650731
Male                         3.692692

In [31]:
# Q6. Occupation Analysis
# Find the number of customers in each occupation  and calculate the average income and account balance for each occupation.

In [32]:
Occupation_analyse = df.groupby("Occupation").agg(
    average_Annual_Income=("Annual_Income","mean"),
    average_Account_Balance = ("Account_Balance","mean")
)
print(Occupation_analyse)

               average_Annual_Income  average_Account_Balance
Occupation
Business                71485.604106            122364.549643
Professional            71704.873846            116548.290615
Retired                 65001.807229            102522.441135
Salaried                70093.420195            143627.168152
Self-Employed           67328.440367            118909.989375
Student                 74053.523669            148035.095313

In [33]:
 # Q7. City Analysis
# Find the top 10 cities having the highest number of customers.
City_Analysis = df.groupby("City").size().sort_values(ascending=False).head(10)
print(City_Analysis)

City
Delhi        191
Ahmedabad    179
Pune         176
Noida        172
Jaipur       171
Hyderabad    169
Kolkata      162
Chennai      161
Lucknow      161
Mumbai       157
dtype: int64

In [34]:
# Q8. Account Type Analysis
# For each Account_Type, find the number of customers, average account balance, average income, and average monthly transactions.
Account_Type_Analysis=df.groupby("Account_Type").agg(
    number_of_customers=("Gender","count"),
    average_account_balance=("Account_Balance","mean"),
    average_income=("Annual_Income","mean"),
    average_monthly_transactions=("Transactions_Per_Month","mean")
)
print(Account_Type_Analysis)

              number_of_customers  average_account_balance  average_income  \
Account_Type
Current                       369            116731.442500    71914.176152
Salary                        398            115036.767423    69720.060302
Savings                      1233            135736.536768    69639.034063

              average_monthly_transactions
Account_Type
Current                          19.065041
Salary                           18.924623
Savings                          19.239254

In [35]:
# Q9. Credit Score Classification
# Create these categories based on Credit_Score:

# Excellent → 750+
# Good → 700–749
# Average → 650–699
# Poor → Below 650

# Then find the number of customers in each category.


df["Credit_Category"] = np.select(
    [
        df["Credit_Score"] >= 750,
        df["Credit_Score"] >= 700,
        df["Credit_Score"] >= 650
    ],
    [
        "Excellent",
        "Good",
        "Average"
    ],
    default="Poor"
)

print(df[["Credit_Score", "Credit_Category"]])

      Credit_Score Credit_Category
0            784.0       Excellent
1            736.0            Good
2            730.0            Good
3            637.0            Poor
4            635.0            Poor
...            ...             ...
1995         753.0       Excellent
1996         722.0            Good
1997         815.0       Excellent
1998         643.0            Poor
1999           NaN            Poor

[2000 rows x 2 columns]

In [36]:
 # Q10. Loan Analysis
# Find:

# Total number of customers having a loan
# Total loan amount
# Average loan amount
# Median loan amount
# Average interest rate
# Most common loan type
Loan_Analysis =df.groupby("Loan_Type").agg(
    number_customer_loan=("Loan_Type","count"),
    total_loan_amount=("Loan_Amount","sum"),
    avg_loan_amount=("Loan_Amount","mean"),
    median_loan_amount=("Loan_Amount","median"),
    avg_interest_rate=("Interest_Rate","mean")
)
print(Loan_Analysis)

           number_customer_loan  total_loan_amount  avg_loan_amount  \
Loan_Type
Auto                        188         97733000.0    519856.382979
Business                    189         90168100.0    477079.894180
Education                   202         95867000.0    474589.108911
Home                        215        114774600.0    533835.348837
Personal                    187         84110300.0    449787.700535

           median_loan_amount  avg_interest_rate
Loan_Type
Auto                 355850.0          13.450479
Business             344400.0          12.735556
Education            341000.0          12.880495
Home                 328700.0          12.563023
Personal             296900.0          12.134171

In [37]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 20 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer_ID             2000 non-null   int64
 1   Customer_Name           2000 non-null   str
 2   Age                     2000 non-null   int64
 3   Gender                  2000 non-null   str
 4   City                    2000 non-null   str
 5   State                   2000 non-null   str
 6   Occupation              1970 non-null   str
 7   Account_Type            2000 non-null   str
 8   Annual_Income           2000 non-null   float64
 9   Account_Balance         1975 non-null   float64
 10  Credit_Score            1965 non-null   float64
 11  Transactions_Per_Month  2000 non-null   int64
 12  Loan_Type               981 non-null    str
 13  Loan_Amount             2000 non-null   float64
 14  Interest_Rate           2000 non-null   float64
 15  Payment_Channel         2000 non-null   str
 16  Tenure_Years            2000 non-null   int64
 17  Customer_Satisfaction   1970 non-null   float64
 18  Churn                   2000 non-null   str
 19  Credit_Category         2000 non-null   str
dtypes: float64(6), int64(4), str(10)
memory usage: 312.6 KB

In [38]:
# Most common loan type
#         ↓
# value_counts()
#         ↓
# idxmax()

# So don't try to put most_common_loan_type inside your agg() here.


most_comman_loan_type= df["Loan_Type"].value_counts().idxmax()
print("most_comman_loan_type:",most_comman_loan_type)

most_comman_loan_type: Home

In [39]:
# Q11. High-Risk Customers
# Find customers who satisfy at least two of these conditions:

# Credit score < 650
# Loan amount > ₹10,00,000
# Interest rate > 15%
# Account balance < ₹20,000

# Display their Customer_ID, Customer_Name, Credit_Score, Loan_Amount, Interest_Rate, and Account_Balance.
# Q11. High-Risk Customers

risk_count = (
    (df["Credit_Score"] < 650).astype(int)
    + (df["Loan_Amount"] > 1000000).astype(int)
    + (df["Interest_Rate"] > 15).astype(int)
    + (df["Account_Balance"] < 20000).astype(int)
)

df["risk"] = np.select(
    [
        risk_count >= 3,
        risk_count == 2,
        risk_count == 1
    ],
    [
        "High Risk",
        "Medium Risk",
        "Low Risk"
    ],
    default="Safe"
)

risk1 = df[
    df["risk"].isin(["High Risk", "Medium Risk"])
][[
    "Customer_ID",
    "Customer_Name",
    "Credit_Score",
    "Loan_Amount",
    "Interest_Rate",
    "Account_Balance"
]]

risk1

,Customer_ID,Customer_Name,Credit_Score,Loan_Amount,Interest_Rate,Account_Balance
4,100005,Sneha,635.0,775800.0,15.75,239069.97
6,100007,Simran,621.0,453600.0,17.97,24654.66
8,100009,Nikhil,743.0,1020300.0,16.54,144805.10
63,100064,Vivaan,587.0,1127600.0,17.73,118156.15
119,100120,Vikash,601.0,287300.0,17.25,NaN
...,...,...,...,...,...,...
1920,101921,Ishita,646.0,85200.0,15.41,14920.19
1932,101933,Aditya,634.0,614800.0,17.16,81659.89
1949,101950,Aditya,796.0,1292900.0,16.60,213821.65
1959,101960,Aditya,764.0,1008600.0,17.32,40974.07
1977,101978,Arjun,780.0,916400.0,15.38,15143.56

In [40]:
# Q12. Correlation Analysis
# Find the correlation between:

# Annual_Income and Loan_Amount
# Credit_Score and Loan_Amount
# Annual_Income and Annual_Income
# Transactions_Per_Month and Account_Balance

Correlation_Analysis=(df["Annual_Income"].corr(df["Loan_Amount"]),
                      df["Credit_Score"].corr(df["Loan_Amount"]),
                      df["Annual_Income"].corr(df["Annual_Income"]),
                      df["Transactions_Per_Month"].corr(df["Account_Balance"])
                     )
print(Correlation_Analysis)

(np.float64(-0.019639667543711496), np.float64(-0.004471206916791463), np.float64(1.0), np.float64(-0.011507078872313083))

In [41]:
# Q13. Outlier Detection — IQR
# Using the IQR method, detect outliers in:

# Annual_Income
# Account_Balance
# Loan_Amount

# Find Q1, Q3, IQR, lower limit, upper limit, and number of outliers.
q1,q3=np.percentile(df["Annual_Income"],[25,75])
print("q1:",q1)
print("q3:",q3)
IQR = (q3-q1)
print(IQR)
lower_limit=q1-1.5 *IQR
upper_limit=q3+1.5*IQR
print("lower_limit:",lower_limit)
print("upper_limit:",upper_limit)

q1: 34575.0
q3: 84450.0
49875.0
lower_limit: -40237.5
upper_limit: 159262.5

In [42]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 21 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer_ID             2000 non-null   int64
 1   Customer_Name           2000 non-null   str
 2   Age                     2000 non-null   int64
 3   Gender                  2000 non-null   str
 4   City                    2000 non-null   str
 5   State                   2000 non-null   str
 6   Occupation              1970 non-null   str
 7   Account_Type            2000 non-null   str
 8   Annual_Income           2000 non-null   float64
 9   Account_Balance         1975 non-null   float64
 10  Credit_Score            1965 non-null   float64
 11  Transactions_Per_Month  2000 non-null   int64
 12  Loan_Type               981 non-null    str
 13  Loan_Amount             2000 non-null   float64
 14  Interest_Rate           2000 non-null   float64
 15  Payment_Channel         2000 non-null   str
 16  Tenure_Years            2000 non-null   int64
 17  Customer_Satisfaction   1970 non-null   float64
 18  Churn                   2000 non-null   str
 19  Credit_Category         2000 non-null   str
 20  risk                    2000 non-null   str
dtypes: float64(6), int64(4), str(11)
memory usage: 328.2 KB

In [43]:
q1,q3=np.percentile(df["Account_Balance"],[25,75])
print("q1:",q1)
print("q2:",q3)
lower_limit=q1-1.5*IQR
upper_limit=q3+1.5*IQR
print("lower_limit:",lower_limit)
print("upper_limit:",upper_limit)

q1: nan
q2: nan
lower_limit: nan
upper_limit: nan

In [44]:
q1,q3=np.percentile(df["Loan_Amount"],[25,75])
print("q1:",q1)
print("q2:",q3)
IQR = (q3-q1)
print(IQR)
lower_limit=q1-1.5*IQR
upper_limit=q3+1.5*IQR
print("lower_limit:",lower_limit)
print("upper_limit:",upper_limit)

q1: 0.0
q2: 328025.0
328025.0
lower_limit: -492037.5
upper_limit: 820062.5

In [45]:
 # Q14. Z-Score Analysis
# Calculate the Z-score for:

# Annual_Income
# Account_Balance
# Credit_Score
# Loan_Amount

# Find customers whose absolute Z-score is greater than 3.
mean =df["Annual_Income"].mean()
std=df["Annual_Income"].std()
Z_Score_Analysis=(df["Annual_Income"]-mean)/std
print(Z_Score_Analysis)

0      -0.720545
1      -0.366804
2      -0.105518
3       0.048573
4      -0.409682
          ...
1995    0.015075
1996   -0.228792
1997   -0.482038
1998   -0.286409
1999   -0.679008
Name: Annual_Income, Length: 2000, dtype: float64

In [46]:
mean =df["Account_Balance"].mean()
std=df["Account_Balance"].std()
Z_Score_Analysis=(df["Account_Balance"]-mean)/std
print(Z_Score_Analysis)

0       1.463651
1      -0.333386
2      -0.317472
3      -0.250315
4       0.357592
          ...
1995   -0.158919
1996    1.114989
1997   -0.356993
1998   -0.266509
1999   -0.164025
Name: Account_Balance, Length: 2000, dtype: float64

In [47]:
mean =df["Credit_Score"].mean()
std=df["Credit_Score"].std()
Z_Score_Analysis=(df["Credit_Score"]-mean)/std
print(Z_Score_Analysis)

0       1.120805
1       0.388057
2       0.296463
3      -1.123237
4      -1.153768
          ...
1995    0.647572
1996    0.174339
1997    1.594039
1998   -1.031644
1999         NaN
Name: Credit_Score, Length: 2000, dtype: float64

In [48]:
# Q15. Log-Normal Distribution Analysis
# Check whether Annual_Income, Account_Balance, and Loan_Amount are right-skewed.

# Calculate their skewness before and after applying log1p() and compare the results.

In [49]:
# Q15. Log-Normal Distribution Analysis
# Check whether Annual_Income, Account_Balance, and Loan_Amount are right-skewed.
column=df[["Annual_Income","Account_Balance","Loan_Amount"]]
for col in column:
     # Skewness before log
    before=df[col].skew()

     # Apply log1p
    log_data = np.log1p(df[col])
    

    after=pd.Series(log_data).skew()

    print(col)
    print("Before:", before)
    print("After :", after)
    print()

    
    
# Calculate their skewness before and after applying log1p() and compare the results.

Annual_Income
Before: 8.269119930632995
After : 0.22314149660077845

Account_Balance
Before: 13.715405256065326
After : 0.35673759707024266

Loan_Amount
Before: 3.744407607638952
After : 0.06529561303256544

In [50]:

# Q16. Customer Segmentation
# Divide customers into four groups based on income and account balance:

# High Income + High Balance
# High Income + Low Balance
# Low Income + High Balance
# Low Income + Low Balance

# Compare the number of customers, average credit score, average transactions, and churn rate for each segment.

In [51]:
# Q16. Customer Segmentation
# Divide customers into four groups based on income and account balance:

# High Income + High Balance
# High Income + Low Balance
# Low Income + High Balance
# Low Income + Low Balance

# Find median values
income_median = df["Annual_Income"].median()
balance_median = df["Account_Balance"].median()

# Create customer segments
df["Customer_Segment"] = np.where(
    (df["Annual_Income"] >= income_median) & 
    (df["Account_Balance"] >= balance_median),
    "High Income + High Balance",

    np.where(
        (df["Annual_Income"] >= income_median) & 
        (df["Account_Balance"] < balance_median),
        "High Income + Low Balance",

        np.where(
            (df["Annual_Income"] < income_median) & 
            (df["Account_Balance"] >= balance_median),
            "Low Income + High Balance",
            "Low Income + Low Balance"
        )
    )
)

# See the result
df[["Annual_Income", "Account_Balance", "Customer_Segment"]].head(10)

   Annual_Income  Account_Balance            Customer_Segment
0        16300.0        582230.23   Low Income + High Balance
1        42700.0         24690.72    Low Income + Low Balance
2        62200.0         29627.96   High Income + Low Balance
3        73700.0         50463.73   High Income + Low Balance
4        39500.0        239069.97   Low Income + High Balance
5        56200.0         75985.78  High Income + High Balance
6        10900.0         24654.66    Low Income + Low Balance
7        35900.0        231920.04   Low Income + High Balance
8        73900.0        144805.10  High Income + High Balance
9        29000.0        121763.37   Low Income + High Balance

In [52]:
# Q18. Banking Performance Score
# Create a combined score using:

# Credit_Score
# Annual_Income
# Account_Balance
# Transactions_Per_Month
# Customer_Satisfaction

# Standardize/normalize these variables and create a Financial/Banking Performance Score.